config/routes.rb
CollegeConnection::Application.routes.draw do
  devise_for :users

  resources :quizzes
  resources :users
  resources :majors
  resources :activities
  
  
  root :to => "users#welcome"

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
before_filter :authenticate_user!

  # GET /quizzes
  # GET /quizzes.json
  def index
      @quizzes = Quiz.all  
      
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quizzes }
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/new
  # GET /quizzes/new.json
  def new
    @quiz = Quiz.new
    @quiz.q1=Array.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = current_user.quiz.find(params[:id])
    @activities = Activity.all
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
  	if(current_user.quiz != nil)
      current_user.quiz.destroy
    end
    
    @quiz = Quiz.new(params[:quiz])
    @quiz.userName=current_user.name
    @quiz.user_id=current_user.id
    @activities = Activity.all  
    if current_user.position == "High School"
       @quiz.q3="High School"
       @quiz.q4= "High School"      
    else
       @quiz.q3="College"
       @quiz.q5= "None"
    end
    respond_to do |format|
      if @quiz.save
        current_user.quiz=@quiz
        format.html { redirect_to @quiz, notice: 'Thank You for Taking the Quiz!.' }
        format.json { render json: @quiz, status: :created, location: @quiz }
      else
        format.html { render action: "new" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quizzes/1
  # PUT /quizzes/1.json
  def update
    @quiz = Quiz.find(params[:id])
    
    respond_to do |format|
      if @quiz.update_attributes(params[:quiz])
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz, html: {class: "nice"}) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.position== "College" %>
  <div class="field">
    <h5>Current Major</h5><br />
    <%= f.collection_select(:q1, Major.all, :name, :name, :prompt => "Select a Major") %>
  </div>
  
  <% else %>
   <div class="field">
    <h5>Choose your top three choices for a possible major. <br />
    If you dont have three choices, leave the selection box as is. <br />
    Your first choice will hold the most weight in the matching process, <br />
    while your last choice will hold the least weight.  <br />
    Please do not pick the same major twice. </h5><br />
    <h5> Choice 1  </h5>
    <%= f.collection_select(:q1, Major.all, :name, :name, {:prompt => "Select a Major"}, {:id => "dropdown_1", :name => "quiz[q1][]"}) %></br>
    <h5> Choice 2  </h5>
    <%= f.collection_select(:q1, Major.all, :name, :name, {:prompt => "Select a Major"}, {:id => "dropdown_2", :name => "quiz[q1][]"}) %></br>
    <h5> Choice 3  </h5>
    <%= f.collection_select(:q1, Major.all, :name, :name, {:prompt => "Select a Major"}, {:id => "dropdown_2", :name => "quiz[q1][]"}) %>
  </div>
  
  
  <% end %>
    
    
  <div class="field">
    <h5>Activites</h5><br />
    <% for activity in Activity.find(:all) %>
    <div>
       <%= f.check_box(:q2, {:multiple=> true}, activity.name, nil) %> <%=activity.name %>
    </div>
  <% end %>
  </div>
  
  <% if current_user.position == "College" %>
  <div class="field">
  <h5>Your School</h5><br />
    <%= f.collection_select(:q4, School.all, :name, :name, :prompt => "Select Your School") %><br /><br />
  </div>
  
  <% else %>
  
  <div class="field">
  <h5>Schools You Are Interested In</h5><br />
  <% for school in School.find(:all) %>
   <div>
   <%= f.check_box(:q5, {:multiple=> true}, school.name, nil) %> <%= %> <%=school.name %>
   </div>
   <% end %>
  </div>
  
  <% end %>
  
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
  
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/new.html.erb
<h3>Fill out the following questions to find students like you! </h3>
<p> If you are a high school student, select answers based on your interests. If you are a
college student, select activities that you are a part of. </p><br />

<div class= "form">
	<%= render 'form' %>
</div>
<%= link_to 'Back', users_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'View Your Matches', users_path %>